services:
  db:
    image: mysql:8.0
    container_name: ps_vendas_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vendas
      MYSQL_USER: vendas
      MYSQL_PASSWORD: vendas
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
