services:
  db:
    image: postgres:16-alpine
    container_name: ps_vendas_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: vendas
      POSTGRES_PASSWORD: vendas
      POSTGRES_DB: vendas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
